### ISSUE TITLE
Remove bower depedency

### ISSUE THREAD

**Issue by donaldwasserman** [ecraft/ember-cli-opbeat#17]
I've submitted a PR to remove bower as a dependency.

**Comment by olleolleolle** [comment]
This is cool work. 

Moving past Bower is good. 

This takes us to a new major version of that packager, too. I guess it's inevitable, progress.

**Comment by olleolleolle** [comment]
#18 fixed this.

**Comment by olleolleolle** [comment]
Thanks for caring about Opbeat. Ciao! :hearts: :yellow_heart: :green_heart: :blue_heart: :purple_heart:
